OpenACCUserGroup/OpenACCV-V

Tests/atomic_capture_expr_plus_x.c
`totals` is allocated with 11 elements on the host.  All 11 elements are accessed in the parallel construct, but only 10 are allocated on the device by the `copy` clause.
=> Fix atomic_capture_expr_plus_x.c totals subarray

Tests/loop_collapse_force.c
Testing force modifier to collapse clause.
New feature to 3.3 (along with multiple levels of gang parallelism).
Line 787 of OpenACC spec 3.3.
=> Testing force collapse loop

Tests/acc_copyin_async.c, Tests/acc_delete_finalize_async.c
added wait directive before exit delete directive in acc_delete_finalize_async.c
also addressed failing acc copyin async test. 
still may be more issues related to 39, wouldn't close yet. however didn't see other instances of this issue this time around.
=> addressed issue #39, still in progress..

Tests/acc_hostptr.F90
OpenACC Spec V: 3.3
Feature is unimplemented, as well as the use of acc_create and acc_delete in this test
Tested using NVHPC/23.5 on V100
=> New Fortran Routine Test for acc_hostptr

Tests/parallel_loop_block.F90
OpenACC Spec V: 3.1 
Feature is unimplemented
Tested using NVHPC/23.5 on V100
Example provided: https://www.openacc.org/blog/announcing-openacc-31
=> New Fortran block construct

Tests/acc_deviceptr.F90, Tests/acc_map_data.F90, Tests/acc_unmap_data.F90
This patch fixes #58. Arrays are declared with default lowerbound of `1`. Arrasy section cannot use lower bound of `0`.
=> Fix invalid lower bound

Tests/serial_loop_reduction_bitand_general.F90
`a` is declared as `a(N)` but is iterated over `LOOPCOUNT`. Also it is in a `copyin` clause with the section `1:LOOPCOUNT`. It seems `a` should be declared as `a(LOOPCOUNT)`. 
If `a` is delcared as `a(N)` the subscript used in the copyin clause is wrong.
=> Fix declaration of a(N) to a(LOOPCOUNT)

Tests/serial_loop_reduction_bitand_loop.F90
Array `a` and `b` have rank 2 but they are referenced with a single subscript. Update the test so the array reference have the correct number of subscript. 
This was detected by flang.
=> Fix reference to rank 2 array with a single subscript

Tests/acc_free.F90, Tests/acc_malloc.F90
Add `CALL` statement for subroutine calls. 
This fixes #68
=> Use CALL statement for subroutine calls

Tests/declare_function_scope_copy.F90
`copyin_copyout_test` is called like a subroutine with the `CALL` statement but it was a function. It seems there is no reason that it is a function because no return value is produced. Switch it to a subroutine so no error are raised on call statements. 
This fixes #62
=> Switch copyin_copyout_test to subroutine

Tests/acc_hostptr.F90
This patch fixes #60. Call to `acc_delete` is missing an argument.
=> Fix call to acc_delete with no arg

Tests/acc_deviceptr.F90
This patch fixes #59. The `VALUE` attribute should not be used on non dummy argument variable.
=> Remove VALUE attribute from non dummy arguments

Tests/serial_implicit_data_attributes.c
Fixed test 1 logic, was unclear before. All tests pass with nvc 23.9 now. 
Some tests are failing with 24.3 but passing with 23.9
=> serial implicit attributes test update

Tests/acc_testsuite.h, Tests/acc_testsuite_declare.h
* Fix Issue #91
Since C23, C defines `true` and `false` as keywords to represent predefined constants of type 'bool' (alias _Bool).
C since C99 provides 'stdbool.h' which can be used both with C23 and older C versions; hence, replace all
`typedef enum { false, true } bool;`
by
`#include <stdbool.h>`
=> Use '#include <stdbool.h>' instead of a typedef for C23 compat

Tests/copy_copyout.c, Tests/copy_copyout.cpp
This test program is designed to evaluate the behavior of using copy and copyout clauses together in OpenACC directives (#pragma acc parallel loop). Each test function performs simple computations on scalar or array variables, transferring data to and from the GPU using both copy and copyout on the same variable. The goal is to verify whether these clauses work together, and to ensure the ordering of the clause does not matter.
The use of copy and copyout is defined but the order in which they execute is not defined. As a result, some compilers may fail while others may produce correct results.
T1 and T3 tests scalar addition using a parallel loop with both copy and copyout clauses and a reduction. Checks if the final value matches n. (The Order of the clauses is just reversed)
T2 and T4 …
=> Copy copyout

Tests/acc_create.c, Tests/acc_create.cpp, Tests/acc_create_async.c, Tests/acc_create_async.cpp
This PR fixes OpenACC reference counting tests for acc_create/acc_create_async to correctly verify that copyout doesn't occur due to reference counting behavior (>0).  Due to reference count being equal to 2 (even after the present decrement action decreases the counter to 1), the copyout will not be performed. The tests now have c[x] initialized to be 1, so that when checked later, c[x] can be compared to a non-zero value.
=> fixing acc_create tests

Tests/wait_devnum.c
The grammar production in the standard for 'wait-argument' is [devnum : int-expr : ] [ queues : ] async-argument-list
So the trailing colon for the devnum is required per spec, but the test uses a comma.  This patch corrects the test by replacing the comma with the colon.
=> Correct use of 'devnum' in wait_devnum.c

Tests/set_if.c, Tests/set_if.cpp
This patch fixes two problems with the set_if tests:
First, as acc_get_device_type is a function, the comparison was a function-pointer to integer comparison inside the 'if'.  This operation is ill-formed in C++.  However, this patch changes for both the C and C++ test to make sure we call the function instead.
Second, OpenACC's restrictions in the 'set' section (2.14.3 in
OpenACC3.3) has a restriction of:
"At least one default_async, device_num, or device_type clause must appear".
This patch adds default_async with acc_async_default to both uses of 'set' in both tests.
=> Correct set_if tests

Tests/kernels_num_gangs.cpp, Tests/kernels_num_workers.cpp
'restrict' is only a keyword in C, and it is not a conforming extension to support it in C++, so GCC and Clang both diagnose this. However, most compilers expose '__restrict' as an alias for this in a conforming manner.
This patch changes the uses of 'restrict' in C++ tests to '__restrict' so that these tests can compile.
=> Correct use of 'restrict' in C++ tests.

Tests/parallel_create_zero.c, Tests/parallel_create_zero.cpp
These tests have a few issues, but this patch fixes two of them:
First, it adds the close paren on the 'copyout' clause that was missing.
Second, it corrects the capitalization on the call to 'Test1', which was resulting in the test not being run properly.
This does NOT fix the ill-formed use of `loop` however.
=> Fix two issues in parallel_create_zero

Tests/data_copyout_zero.c, Tests/data_copyout_zero.cpp, Tests/data_create_zero.c, Tests/data_create_zero.cpp, Tests/parallel_copyout_zero.c, Tests/parallel_copyout_zero.cpp, Tests/parallel_create_zero.c, Tests/parallel_create_zero.cpp, Tests/routine_bind_nonprototype_function_nonstring_function.cpp, Tests/routine_bind_nonprototype_function_nonstring_lambda.cpp, Tests/routine_bind_nonprototype_function_string_function.cpp, Tests/routine_bind_nonprototype_function_string_lambda.cpp, Tests/routine_bind_nonprototype_lambda_nonstring_function.cpp, Tests/routine_bind_nonprototype_lambda_nonstring_lambda.cpp, Tests/routine_bind_nonprototype_lambda_string_function.cpp, Tests/routine_bind_nonprototype_lambda_string_lambda.cpp, Tests/routine_bind_prototype_function_nonstring_function.cpp, Tests/routine_bind_prototype_function_nonstring_lambda.cpp, Tests/routine_bind_prototype_function_string_function.cpp, Tests/routine_bind_prototype_function_string_lambda.cpp, Tests/routine_bind_prototype_lambda_nonstring_function.cpp, Tests/routine_bind_prototype_lambda_nonstring_lambda.cpp, Tests/routine_bind_prototype_lambda_string_function.cpp, Tests/routine_bind_prototype_lambda_string_lambda.cpp
The OpenACC 3.3 spec says (2.9 summary): The OpenACC loop construct
applies to a loop which must
immediately follow this
directive.
This patch fixes all(hopefully!) violations of this problem.
=> Fix uses of 'loop' to be followed immediately by a loop.
